version: '3'

services:
   db:
     image: mysql
     volumes:
       - mydb:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: mydb
       MYSQL_USER: root
       MYSQL_PASSWORD: root

volumes:
  mydb: